/**
 * Whole-segment dictionary for path parts and query keys/values.
 * Exact matches are encoded as a compact index instead of character-by-character.
 */
export const SEGMENT_TOKENS = [
  "utm_source", "utm_medium", "utm_campaign", "utm_content", "utm_term", "utm_id",
  "fbclid", "gclid", "gclsrc", "dclid", "msclkid", "twclid", "igshid",
  "_ga", "_gl", "mc_eid", "mc_cid", "_hsenc", "_hsmi",
  "feature", "ref", "ref_src", "ref_url", "source", "src",
  "redirect", "redirect_uri", "return", "return_url", "next", "url",
  "q", "s", "t", "v", "id", "ids", "p", "page", "offset", "limit",
  "sort", "order", "filter", "query", "search", "tag", "tags",
  "category", "type", "format", "view", "mode", "tab", "lang", "locale",
  "hl", "country", "currency", "from", "to", "date", "token", "key",
  "client_id", "client", "response_type", "scope", "state", "code",
  "callback", "jsonp", "ajax", "version", "ver", "width", "height",
  "quality", "zoom", "list", "index", "start", "end", "time",
  "autoplay", "mute", "controls", "embed", "playlist",
  "share", "text", "via", "related", "original_referer",
  "si", "app", "u", "w", "h",
  "google", "facebook", "twitter", "cpc", "email", "newsletter", "organic",
  "referral", "bing", "instagram", "youtube", "direct",
  "true", "false", "json", "html", "xml", "rss",
  "watch", "status", "statuses", "comments", "comment", "posts", "post",
  "article", "articles", "story", "stories", "video", "videos",
  "explore", "discover", "trending", "popular",
  "edit", "create", "update", "download", "uploads", "upload",
  "files", "file", "images", "image", "img", "photos", "photo", "media",
  "static", "assets", "css", "js", "api", "v1", "v2", "v3",
  "graphql", "oauth", "login", "logout", "signin", "signup", "register",
  "auth", "account", "profile", "settings", "dashboard", "admin",
  "wp-content", "wp-admin", "wp-includes", "wp-json", "feed",
  "sitemap", "about", "contact", "help", "support", "blog", "news",
  "products", "product", "item", "items", "shop", "store", "cart",
  "checkout", "wiki", "user", "users", "channel", "track",
  "album", "artist", "collection", "thread", "topic", "forum", "group",
  "r", "dp", "gp", "issues", "pull", "commit", "blob", "tree", "raw",
  "releases", "stargazers", "forks", "projects", "actions",
  "discussions", "questions", "answer", "answers", "in",
  "document", "spreadsheets", "presentation", "forms", "d",
  "maps", "place", "dir", "intent", "hashtag", "reel",
  "amp", "mobile", "home", "default", "main", "pages",
  "archive", "author", "content", "public", "lib", "dist", "build", "vendor",
  "cgi-bin", "scripts", "includes", "plugins", "themes",
  "how-to", "what-is", "best", "top", "new", "old",
  "en", "de", "fr", "es", "it", "pt", "ru", "ja", "zh", "ko",
  "2020", "2021", "2022", "2023", "2024", "2025", "2026", "2027", "2028", "2029", "2030",
  "technology", "programming", "compress", "compression",
  "wp-login", "xmlrpc", "node_modules", "package", "readme", "license",
  "spring", "summer", "fall", "winter", "sale", "promo",
  "authorize", "tweet", "title", "path", "stories",
  "shorts", "live", "clip", "clips", "results", "collections", "catalog",
  "gallery", "compare", "invite", "channels", "events", "groups", "company",
  "jobs", "episode", "show", "preview", "open", "print", "docs",
  "library", "reference", "tutorial", "guide", "manual", "models",
  "project", "packages", "abs", "doi", "pdf", "keywords",
  "gad_source", "gad_campaignid", "wbraid", "gbraid", "yclid", "srsltid",
  "pk_campaign", "pk_source", "pk_kwd", "mtm_campaign", "mtm_source", "mtm_medium",
  "campaign", "medium", "term",
  "use", "using", "with", "your", "our", "the", "and", "for",
  "this", "that", "how", "what", "why", "all", "get", "set", "web",
  "coding", "data", "write", "fast", "works", "better",
  "software", "activity", "parse", "urllib", "requests", "qrcode",
  "en-US", "en-GB", "zh-CN", "pt-BR", "Web", "API", "URL", "Docs", "shortening"
];

export const FILE_EXTENSIONS = [
  "html", "htm", "php", "asp", "aspx", "jsp",
  "json", "xml", "txt", "pdf", "css", "js", "rss", "atom",
  "md", "png"
];
